# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('sum', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Stats',
                'verbose_name': 'Daily total',
            },
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='Network Operator')),
                ('note', models.TextField(blank=True, help_text='Customer services number, top-up and packages details', verbose_name='Notes')),
            ],
            options={
                'verbose_name_plural': 'Networks',
                'verbose_name': 'Network',
            },
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imsi', models.CharField(blank=True, editable=False, max_length=25, null=True)),
                ('no', models.CharField(blank=True, help_text='registered for this SIM', max_length=11, null=True, verbose_name='Phone number')),
                ('serial', models.CharField(blank=True, help_text='The long number written on the SIM', max_length=25, null=True, verbose_name='Serial No')),
                ('ref', models.IntegerField(blank=True, help_text='shows in the sidebar', null=True, verbose_name='Reference #')),
                ('active', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, help_text='Gateway/SIM topup URL', max_length=75, null=True, verbose_name='URL')),
                ('user', models.CharField(blank=True, help_text='Gateway/SIM topup credentials', max_length=25, null=True, verbose_name='Username')),
                ('pwd', models.CharField(blank=True, max_length=25, null=True, verbose_name='Password')),
                ('note', models.TextField(blank=True, help_text='About the package, topup etc.', verbose_name='Any other notes?')),
                ('net', models.ForeignKey(blank=True, help_text='What network operator is it on?', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Net', verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'SIM',
                'verbose_name_plural': 'SIMs',
                'ordering': ('net', 'ref'),
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=15, verbose_name='Phone number')),
                ('txt', models.TextField(verbose_name='Text')),
                ('at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('typ', models.CharField(choices=[('s', 'Sent'), ('r', 'Received')], editable=False, max_length=1, verbose_name='Sent or Received')),
                ('state', models.CharField(blank=True, choices=[('d', 'Delivered'), ('e', 'Expired'), ('f', 'Failed')], editable=False, max_length=1, null=True, verbose_name='Status')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Cat')),
                ('sim', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sms.Sim', verbose_name='SIM')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Tpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tpl', models.TextField(verbose_name='Body')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'verbose_name': 'Template',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Sim'),
        ),
        migrations.AlterUniqueTogether(
            name='sim',
            unique_together=set([('net', 'ref')]),
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together=set([('day', 'sim')]),
        ),
    ]
